//
//  ArchitectureMultipartTests.swift
//  NebulaTests
//
//  Wave N17c — Bodies & downloads. Unit tests for the pure
//  ``NebulaMultipartBuilder`` surface (no URLSession):
//  - A. the builder (pure `Data` composer — parts, boundary, content-type,
//    round-trip parse),
//  - B. the temp-file writer (``file(in:)`` for streaming uploads),
//  - C. ``NebulaMultipartError`` mapping.
//
//  The builder holds no I/O and no `@Sendable` closure — it is pure, so it is
//  unit-tested directly without a `URLSession`. See
//  vault/03-padroes/nebula-bodies-downloads.md.
//

import Testing
import Foundation
@testable import Nebula

@Suite struct ArchitectureMultipartTests {

    // MARK: - A. Builder (pure)

    @Test func partValueSemanticsAndHashable() {
        let field = NebulaMultipartPart.field(name: "title", value: "Nebula")
        #expect(field.name == "title")
        #expect(field.filename == nil)
        #expect(field.contentType == nil)
        #expect(field.body == Data("Nebula".utf8))

        let file = NebulaMultipartPart.file(name: "upload", filename: "f.bin",
                                             contentType: "application/octet-stream",
                                             data: Data([0xDE, 0xAD]))
        #expect(file.filename == "f.bin")
        #expect(file.contentType == "application/octet-stream")
        #expect(file.body == Data([0xDE, 0xAD]))

        // Equatable + Hashable derived.
        #expect(field == NebulaMultipartPart.field(name: "title", value: "Nebula"))
        #expect(field != file)
        #expect(Set([field, file]).count == 2)
    }

    @Test func builderAddingReturnsDistinctCopies() {
        let base = NebulaMultipartBuilder(boundary: "B")
        let one = base.adding(.field(name: "a", value: "1"))
        let two = one.adding(.field(name: "b", value: "2"))
        // Value semantics — base unchanged.
        #expect(base.parts == [])
        #expect(one.parts.count == 1)
        #expect(two.parts.count == 2)
        #expect(one.parts.first?.name == "a")
        #expect(two.parts.last?.name == "b")
        #expect(one.boundary == "B")
    }

    @Test func autoGeneratedBoundaryIsUniqueAndPrefixed() {
        let a = NebulaMultipartBuilder()
        let b = NebulaMultipartBuilder()
        #expect(a.boundary.hasPrefix(NebulaMultipartBuilder.boundaryPrefix))
        // 16 random bytes → 32 hex chars + prefix.
        #expect(a.boundary.count == NebulaMultipartBuilder.boundaryPrefix.count + 32)
        // Random — two builders almost certainly differ.
        #expect(a.boundary != b.boundary)
    }

    @Test func buildProducesFieldPartEncoding() {
        let form = NebulaMultipartBuilder(boundary: "B")
            .adding(.field(name: "title", value: "Nebula"))
            .build()
        #expect(form.boundary == "B")
        #expect(form.contentType == "multipart/form-data; boundary=B")
        let body = String(data: form.data, encoding: .utf8)
        #expect(body == "--B\r\nContent-Disposition: form-data; name=\"title\"\r\n\r\nNebula\r\n--B--\r\n")
    }

    @Test func buildProducesFilePartEncoding() {
        let form = NebulaMultipartBuilder(boundary: "B")
            .adding(.file(name: "upload", filename: "f.bin",
                          contentType: "application/octet-stream", data: Data([0xDE, 0xAD])))
            .build()
        // Binary body bytes — decode the textual envelope as UTF-8, then
        // assert the raw body bytes are present verbatim.
        let prefix = "--B\r\nContent-Disposition: form-data; name=\"upload\"; filename=\"f.bin\"\r\nContent-Type: application/octet-stream\r\n\r\n"
        let suffix = "\r\n--B--\r\n"
        let prefixData = Data(prefix.utf8)
        #expect(form.data.prefix(prefixData.count) == prefixData)
        let suffixData = Data(suffix.utf8)
        #expect(form.data.suffix(suffixData.count) == suffixData)
        // The body bytes sit between the envelope, untouched.
        let bodyStart = prefixData.count
        let bodyEnd = form.data.count - suffixData.count
        #expect(form.data[bodyStart..<bodyEnd] == Data([0xDE, 0xAD]))
    }

    @Test func buildPreservesPartOrdering() {
        let form = NebulaMultipartBuilder(boundary: "B")
            .adding(.field(name: "first", value: "1"))
            .adding(.field(name: "second", value: "2"))
            .adding(.field(name: "third", value: "3"))
            .build()
        let body = String(data: form.data, encoding: .utf8) ?? ""
        // The closing boundary appears once; three parts in order.
        let dispositions = body.components(separatedBy: "\r\n").filter { $0.hasPrefix("Content-Disposition") }
        #expect(dispositions.count == 3)
        #expect(dispositions[0].contains("\"first\""))
        #expect(dispositions[1].contains("\"second\""))
        #expect(dispositions[2].contains("\"third\""))
        #expect(body.components(separatedBy: "--B--\r\n").count == 2)
    }

    @Test func buildEmptyBuilderProducesClosingBoundaryOnly() {
        let form = NebulaMultipartBuilder(boundary: "B").build()
        let body = String(data: form.data, encoding: .utf8)
        #expect(body == "--B--\r\n")
    }

    @Test func builderIsSendableAcrossTask() async throws {
        let builder = NebulaMultipartBuilder(boundary: "B").adding(.field(name: "k", value: "v"))
        let built = try await Task { builder.build() }.value
        #expect(built.boundary == "B")
    }

    // MARK: - B. Temp-file writer

    @Test func fileWritesBuiltDataToTempFile() async throws {
        let form = NebulaMultipartBuilder(boundary: "B")
            .adding(.field(name: "k", value: "v"))
            .build()
        let url = try NebulaMultipartBuilder(boundary: "B")
            .adding(.field(name: "k", value: "v"))
            .file(in: FileManager.default.temporaryDirectory)
        defer { try? FileManager.default.removeItem(at: url) }
        let read = try Data(contentsOf: url)
        #expect(read == form.data)
    }

    @Test func fileDefaultDirectoryIsTemporary() async throws {
        let url = try NebulaMultipartBuilder(boundary: "B").file()
        defer { try? FileManager.default.removeItem(at: url) }
        #expect(url.path.hasPrefix(FileManager.default.temporaryDirectory.path))
    }

    // MARK: - C. Error mapping

    @Test func multipartErrorCoarseKindAndBridge() {
        let err = NebulaMultipartError.buildFailed("boom")
        #expect(err.coarseKind == .network)
        #expect(err.kind == .buildFailed)
        #expect(err.code == "build-failed")
        let bridged = err.toNebulaError(kind: err.coarseKind)
        #expect(bridged.code.domain == "Nebula.NebulaMultipartError")
        #expect(bridged.metadata["NebulaCode"] == "build-failed")
    }

    @Test func multipartErrorIofailedCarriesUnderlying() {
        let nsErr = NSError(domain: "FS", code: 13)
        let box = NebulaError.Box(NebulaError(error: nsErr))
        let err = NebulaMultipartError.ioFailed("io", underlying: box)
        #expect(err.coarseKind == .network)
        #expect(err.underlying != nil)
    }

    @Test func multipartErrorCancelledIsUnknown() {
        #expect(NebulaMultipartError.cancelled().coarseKind == .unknown)
        #expect(NebulaMultipartError.unknown().coarseKind == .unknown)
    }

    @Test func multipartErrorIsSendableAcrossTask() async throws {
        let err = NebulaMultipartError.buildFailed("x")
        let back = try await Task { err }.value
        #expect(back.kind == .buildFailed)
    }
}